language: node_js
node_js:
 - "7"
 - "6"
 - "5.1"

services:
 - docker

before_install:
 - docker pull archisioux/magicmirror

before_script:
 - npm install grunt-cli -g
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 5
script:
- grunt
- npm test
cache:
 directories:
  - node_modules
